spring.application.name=BarberReservation

# database.properties
spring.datasource.url=jdbc:mysql://sql_host:3306/fadebook?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Google OAuth
google.clientId.web=your_web_clientId
google.clientId.ios=your_ios_clientId
google.clientId.android=your_android_clientId

#JWT configuration
jwt.secret=jwt_secret_key
jwt.expiration=3600000

# Khalti (test mode)
khalti.secret-key=your_secret_key
khalti.initiate-url=https://dev.khalti.com/api/v2/epayment/initiate/
khalti.lookup-url=https://dev.khalti.com/api/v2/epayment/lookup/
khalti.return-url=http://localhost:8082/api/payment/khalti/callback
khalti.website-url=http://localhost:8082

# eSewa (Test Mode)
esewa.merchant-id=EPAYTEST
esewa.merchant-secret=8gBm/:&EnhH.1/q
esewa.base-url=https://rc.esewa.com.np/api/epay/main/v2/form/
esewa.success-url=http://localhost:8082/api/payment/esewa/callback
esewa.failure-url=http://localhost:8082/api/payment/esewa/failure

logging.level.org.springframework.security=DEBUG
